@echo off
echo Building Drug Tool Lookup application...

echo Installing dependencies...
call npm install

echo Building production version...
call npm run build

echo Starting production server...
node server.js